version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount for development (uncomment for dev mode)
      # - .:/app
      # - /app/node_modules
      - /tmp/uploads:/tmp/uploads
    restart: unless-stopped
    networks:
      - app-network

  # Development service with hot reload
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/uploads:/tmp/uploads
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
